### ISSUE TITLE
Can't launch with latest Rails version

### ISSUE THREAD

**Issue by sowenjub** [jesseduffield/lazy_migrate#2]
Hey Jesse, I tried running `LazyMigration.run` with rails `6.0.3.2` and I hit this error:

> ArgumentError: wrong number of arguments
> from ~.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:1028:in `initialize'

I assume it comes from this line:
https://github.com/jesseduffield/lazy_migrate/blob/498c66273c9111380a0937ec6718c39bde043864/lib/lazy_migrate/new_migrator_adapter.rb#L18

And is a consequence of this change https://github.com/rails/rails/commit/7cc27d749c3563e6b278ad01d233cb92ea3b7935#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6R1018

**Comment by gmhawash** [comment]
Same issue with Rails6

**Comment by jesseduffield** [comment]
Interesting, I'll take a look

**Comment by PikachuEXE** [comment]
Any update ? ;)

**Comment by PikachuEXE** [comment]
I got this monkey patch
```ruby
LazyMigrate::NewMigratorAdapter.class_eval do
  def initialize
    # TODO: consider making this a method rather than an instance variable
    # considering how cheap it is to obtain
    @context = ActiveRecord::MigrationContext.new(Rails.root.join('db', 'migrate'), ActiveRecord::SchemaMigration)
  end
end
```

Tested on rails 6.0.3.4

**Comment by PikachuEXE** [comment]
Maybe we should consider #3 sooner since rails 6.1 is on RC already?
